### ISSUE TITLE
Serverless hangs on "Removing old artifacts..."

### ISSUE THREAD

**Issue by abagshaw** [kuashe/serverless-async-await#3]
First off, awesome plugin. This is so much easier to use than [serverless-webpack](https://github.com/elastic-coders/serverless-webpack) to get the `async`/`await` functionality I need.

One odd issue I encountered: When using `serverless deploy`  everything works as expected up to and including successfully deploying the function, but after that I get:

`Serverless: Removing old artifacts...`

And it hangs permanently on that. I'm on Win 10 deploying to Google Cloud Functions if that makes any difference. I tried enabling logs with setting the `SLS_DEBUG` env variable to `*` but I didn't see anything new outputted - maybe I'm supposed to be looking somewhere else?

When not using the serverless-async-await plugin, the `Removing old artifacts...` step completes successfully in a second or two.

Any ideas? Thanks very much!

**Comment by kuashe** [comment]
I managed to reproduce the issue only if there is no handler specified in the `serverless.yml`

Is this an old or a fresh service ?

Also can you try to `npm update` the plugin and serverless as well ?

**Comment by abagshaw** [comment]
I tried creating a new service, re-installing serverless globally and freshly installing the plugin locally but it still hangs, but oddly now it hangs just before showing `Serverless: Removing old artifacts...`  (right after showing the URL trigger of the function)

If it's of any help, here are my configuration files:

**serverless.yml**:

```
service: user-manage-function

provider:
  name: google
  runtime: nodejs
  project: firstproject
  credentials: keyfile.json

plugins:
  - serverless-google-cloudfunctions
  - serverless-async-await

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: mainHandler
    events:
      - http: user-manage-function
```

**package.json**:

```
{
  "name": "user-manage-function",
  "version": "0.1.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "serverless-google-cloudfunctions": "^1.1.1",
    "@google/cloud-debug": "latest"
  },
  "devDependencies": {
    "serverless-async-await": "^1.1.4"
  }
}
```
